### ISSUE TITLE
"Access" facet

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#127]
@caseyedavis12 : What values show under the facet? just "Online" + "All Records"?

besides that:
- Will these be clear enough, or do we need explanatory blurbs like on AAPB? Hopefully not...
- We will use the same kind of logic as AAPB, ie selecting one unselects the other?
- On other facets, if you click on a currently selected facet value, it unselects it. Does that same model work here, or should only the unselected one be clickable?
- This is no explicit statement of access on the record itself, right?
- "Online" or whatever we call it needs to be applied by default on searches.

**Comment by caseyedavis12** [comment]
@mccalluc: What values show under the facet? just "Online" + "All Records"? YES

  *   We will use the same kind of logic as AAPB, ie selecting one unselects the other? YES
  *   On other facets, if you click on a currently selected facet value, it unselects it. Does that same model work here, or should only the unselected one be clickable? YES
  *   This is no explicit statement of access on the record itself, right? If it is not available online, please use this message under the video thumbnail like on AAPB: "Please note: This content has not been digitized. For inquiries regarding access or if you are interested in sponsoring the digitization of this program, please contact us at openvault@wgbh.org"
  *   "Online" or whatever we call it needs to be applied by default on searches. YES

Instead of just "Online" could it say "Available Online"

**Comment by mccalluc** [comment]
(We also need the same kind of logic from AAPB that if the facet value is unspecified on a request, we add the default and redirect.)
