### ISSUE TITLE
Top menu is missing for one of the medium screen widths; present for all others

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3#180]
**menu shows for wide screen:**
![image](https://cloud.githubusercontent.com/assets/1507490/12986658/7b17c9de-d0c6-11e5-8fe5-1bb01c1ce443.png)

**... and for narrow screen...**
![image](https://cloud.githubusercontent.com/assets/1507490/12986700/aedc634c-d0c6-11e5-9a5b-9cb485022c6b.png)

**... but not for middle screen :frowning::**
![image](https://cloud.githubusercontent.com/assets/1507490/12986684/97299b8e-d0c6-11e5-8cf9-aa770713a28e.png)

**Done when** the top menu is present for all screen widths.

**Comment by caseyedavis12** [comment]
@afred: for the narrow screen, can you stack the three sections on the menu?


WGBH Series

Scholar Exhibits

Special Collections

**Comment by afred** [comment]
filed #181

**Comment by mccalluc** [comment]
@afred / @caseyedavis12 : FWIW: I think I intentionally hid the banner links in sm, and the real bug is that I missed xs. When there's less real estate, I think it's really good to ask whether a given set of links needs to be repeated 3 times on the page. 

If anything, I think the xs banner needs to be even smaller, rather than larger.

If you believe than having more links on on XS is really the right direction, please check the site out on your phone and double check that you want that much of the screen used on every page. Thanks.

**Comment by afred** [comment]
@mccalluc @caseyedavis12 :+1: for less link repetition on smaller screens.

**Comment by caseyedavis12** [comment]
@mccalluc: less repetition on XS is a good idea
