### ISSUE TITLE
Media requiring login authentication

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#233]
Which media files require the user to login to view? Is this information present in the PBCore?

**Comment by mccalluc** [comment]
In the PBCore it's expressed as:
```
  <pbcoreAnnotation annotationType="Password">YES</pbcoreAnnotation>
```

In the UI it looks like this
<img width="652" alt="screen shot 2016-02-18 at 9 42 26 am" src="https://cloud.githubusercontent.com/assets/730388/13146543/4d962998-d624-11e5-81c9-e19082022b04.png">

Is this good enough, or do you need some tweaks? (rhetorical question.) Note that this is completely client side: is that acceptable? Since I don't think we're going to implement security on the actual media delivery, just adding a server-side check wouldn't actually give us that much.

**Comment by caseyedavis12** [comment]
@mccalluc: We need to present this to legal to make sure it is sufficient. More soon.

**Comment by mccalluc** [comment]
@caseyedavis12 : when is that meeting scheduled for?

**Comment by caseyedavis12** [comment]
@mccalluc: Our next meeting with legal counsel is on Thursday at 2pm.

**Comment by mccalluc** [comment]
@caseyedavis12 : what was the outcome?

**Comment by caseyedavis12** [comment]
@mccalluc: still in review by legal counsel. I will definitely let you know when they offer their opinion...this is one of about 9 items on their plate for MLA currently.
________________________________

**Comment by mccalluc** [comment]
Done.
