### ISSUE TITLE
Bring all these projects up to the the same ruby version.

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#351]

**Comment by mccalluc** [comment]
```
$ for PROJ in openvault3 openvault3_deploy mla-playbooks aws-wrapper; do echo $PROJ '-->' ; curl https://raw.githubusercontent.com/WGBH/${PROJ}/master/.ruby-version ; echo ; done
openvault3 -->
2.0.0-p353
openvault3_deploy -->
Not Found
mla-playbooks -->
Not Found
aws-wrapper -->
2.2.3
```
So I'll try bringing this up to 2.2.3

**Comment by afred** [comment]
@mccalluc this will be good for development, but won't have any effect on AWS instances, because they currently aren't using RVM. [There is a ticket](https://github.com/WGBH/mla-playbooks/issues/59) to try RVM with the mla-playbooks.

Also, I don't think there is any _technical_ requirement that these projects all run the same version, as long as one project is not invoking code from another.

**Comment by mccalluc** [comment]
Yeah, I'm only proposing this because of the slight annoyance when a developer is checking out projects the first time. No larger motivation, really.

**Comment by mccalluc** [comment]
(For future reference, using RVM in deployment turned out not to work well: Seemed to be no faster, and there is a chicken-and-egg problem with the passenger gem. Closing.)
