### ISSUE TITLE
Open Vault Metadata Decisions Spreadsheet

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/openvault3#38]
This spreadsheet lists the PBCore field, and if and how each should be displayed on Open Vault.

[OpenVault_Metadata_Decisions_160105.xlsx](https://github.com/WGBH/openvault3/files/78431/OpenVault_Metadata_Decisions_160105.xlsx)

**Comment by caseyedavis12** [comment]
@mccalluc: Please disregard the column that says "Normalization Needed." This is outdated as all fields will be normalized by the time you receive the PBCore XML.

**Comment by mccalluc** [comment]
@caseyedavis12 : I'm not going to look closely at this until I see xml, but here are some points that might need clarification. If it's all under control, great.

- In the spreadsheet, 8 fields are identified as "facets": The UI only accommodates 6 filters.
- To confirm, we will not have publisher roles?
- `pbcoreAnnotation type="Thumbnail"` and `pbcoreAnnotation type="Transcript"`: These are booleans, right, and not URLs?
- `pbcoreAnnotation type="Outside URL"`: So to distinguish AAPB and News I'll look at the hostname? Any other value will be an error?
- `pbcoreAnnotation type="Geoblock"` and `pbcoreAnnotation type="Password Restriction"`: booleans?
- genre and topic exist only at the series level
- `Playlist Group/Order`: Not clear to me what's going in here. In particular, where will the total count be stored so that record 1 of 3 knows it is "of 3"?

**Comment by Muraszko** [comment]
@mccalluc Here is the updated version of the spreadsheet:
[OpenVault_Metadata_Decisions_01152016.xlsx](https://github.com/WGBH/openvault3/files/91777/OpenVault_Metadata_Decisions_01152016.xlsx)
We changed the two instantiation elements to annotations (Duration, Media Type).

**Comment by mccalluc** [comment]
I think all the fields are in place in the UI. Gaps should be their own bugs. Closing.
