### ISSUE TITLE
Get the FM->PBCore XSLT under version control

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#60]
@foo4thought : Could you put the XSLT you've written under lib here? 
- Version control is just a good thing, in general.
- At some point I might be wondering if it's possible for a particular value to be repeated, and being able to refer to the source code would be useful.

**Comment by foo4thought** [comment]
LOL.

OK, but githubbing the XSL is kinda silly because it's strictly an internal resource of a "scratch" FileMaker file that is meant to be used only once; all will persist for potential reference somewhere in the MLA part of the deptfs (network) file share.

-- kevin carter

-- programmer analyst

-- wgbh educational foundation

-- 1 guest street

-- boston, ma, usa, 02135

-- 6173005923 v/vm/fax

-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and

technology to enlighten and enable

________________________________

**Comment by mccalluc** [comment]
I was under a misimpression: If it's really only used exactly once, then no, I don't need it. Thanks for clarifying.
