### ISSUE TITLE
Should we check that S3 assets are in place on ingest?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#66]
@Muraszko : Would it be good to check that S3 assets are in place during ingest? Perhaps optionally... We would just make a HEAD request, so it'd be some extra traffic, but it'd make me much more confident that everything is in place. Thoughts?

**Comment by Muraszko** [comment]
@mccalluc 
Yes that's a good idea, especially for this initial batch because it's not likely that each record with asset media will be spot checked immediately.

Thinking about future ingest, can you have it make the head requests for only the newly imported records, rather than check every single S3 file the website could be expecting?

**Comment by mccalluc** [comment]
@Muraszko : For future ingests, yeah, it should only be the records that have been modified in FM that would even be in the export, so we wouldn't need to re-check everything.

**Comment by mccalluc** [comment]
Fixed in aee6de84
