### ISSUE TITLE
Which fields are required?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#73]
@caseyedavis12 : sorry if I missed it, but what fields are required? I was expecting there to be a column in the spreadsheet, but just providing a list here would be fine, too. (ie, we don't require a location, but we do require a title.)

**Comment by Muraszko** [comment]
@mccalluc Check the spreadsheet in my last comment on issue #38 
That also has the facet information.

**Comment by mccalluc** [comment]
(We talked; it's not there, but Mike will get it.)

**Comment by Muraszko** [comment]
@mccalluc 
Sorry, yes.  Here are the three fields that every XML record is required to have.
```
<pbcoreAssetType>
<pbcoreAnnotation annotationType="Media Type">
<pbcoreIdentifier source="Open Vault UID">
```
Anything else may or may not have a value.

In the current batch of individual XML files Kevin has sent along there are 61 records that do not have Media Type, so that may be a good test if you were wanted to check for that.  It's on my issues list to fix those records before the website launches.

**Comment by mccalluc** [comment]
@Muraszko : Thanks! (Edge case, but no title is required?)

**Comment by Muraszko** [comment]
That's correct.
Titles can be expressed in
```
<pbcoreTitle titleType="Open Vault Title">
```
But for records that don't have an Open Vault Title, Casey had said she would like the title to be displayed as series, program, program number.  Some records only have either a series or program title.
