### ISSUE TITLE
Could file names in zip be based on ID?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3#93]
@foo4thought : If this is hard, never mind, but would it be possible to have the filenames in the zip be based on the ID. So, instead of 
`2015_OV_MASTERS_FINAL_1000_63588567823889.xml`
we might have
`V_76FF42FB387043579AAE7F39B43D2D1C.xml`
?

The end goal is get access to the xml for a particular record, without loading everything again. A different approach to this would be to set me up with read-only access to the DB, so I could define my own records for export.

**Comment by foo4thought** [comment]
Working on it




-- kevin carter
-- programmer analyst
-- wgbh educational foundation
-- 1 guest street
-- boston, ma, usa, 02135
-- 6173005923 v/vm/fax
-- www.wgbh.org

-- WGBH:  pioneering public education since 1951 with content and
technology to enlighten and enable.


________________________________

**Comment by foo4thought** [comment]
ZIP created containing XML files renamed as you wished.  it's too large to drop here, so email
